name: Packer building a Master Image on Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  packer-build:
    runs-on: ubuntu-latest
    env:
      PACKER_LOG: "1"
      PACKER_LOG_PATH: "packer.log"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Packer init
        run: packer init ./packer

      - name: Packer validate
        run: packer validate -var-file "./packer/win11-azure.auto.pkrvars.hcl" ./packer/win11-azure.pkr.hcl

      - name: Packer build
        run: packer build -on-error=abort -force -var-file="./packer/win11-azure.auto.pkrvars.hcl" ./packer/win11-azure.pkr.hcl
